sudo: required
addons:
  apt:
    update: true

scala:
  - "2.11.11"

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
      language: scala

    - os: osx
      osx_image: xcode9.3

before_install:
  - ./scripts/travis_setup.sh

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - java -version
  - scripts/scalafmt --test
  - sbt sbt-crossproject-test/scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
